version: '3'

services:
    php:
        build: './php'
        env_file:
            - .env
        networks: 
            - backend
        volumes:
            - ./src/api:/var/www/html/
        ports:
            - "9000:9000"
    apache:
        build: './apache'
        depends_on: 
            - php
            - postgres
        networks:
            - frontend
            - backend
        ports:
            - "8080:80"
        volumes:
            - ./dist/:/usr/local/apache2/htdocs/
    postgres:
        build: './postgres'
        networks:
            - backend
        env_file:
            - .env
        ports:
            - "5432:5432"

networks:
    frontend:
    backend:
    